# fly.toml app configuration file generated for painel-financeiro-seleto on 2025-07-26T03:07:08-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'painel-financeiro-seleto'
primary_region = 'gru'

[build]

[[mounts]]
  source = 'sqlite_data'
  destination = '/app/db'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
