@echo off
ECHO Iniciando o servidor Frontend...
start "Frontend" cmd /k "cd /d "C:\Users\Tiago Seman\Desktop\PROJETO FLUXO CAIXA\painel-financeiro-frontend" && npm run dev"

ECHO Iniciando o servidor Backend...
start "Backend" cmd /k "cd /d "C:\Users\Tiago Seman\Desktop\PROJETO FLUXO CAIXA\painel-financeiro-backend" && npm run dev"

ECHO Servidores em processo de inicialização...